test = {   'name': 'q1_3',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(comma_separated, str) and isinstance(space_separated, str)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> len(comma_separated) == 32 # You have the wrong length for comma_separated. Make sure comma_separated appears EXACTLY as described.\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
