test = {   'name': 'q1_3',
    'points': None,
    'suites': [   {   'cases': [   {   'code': ">>> callable(ci_and_hist) and (test_var != None) # Make sure your function returns a string, and doesn't just print one\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> test_var[:29] == 'A 99% confidence interval for'\nTrue", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
