test = {   'name': 'q1_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> 0 < q1_1 < 5\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_1 != 2\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_1 != 3\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> q1_1 != 4\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
